### ISSUE TITLE
Django 4, No module named 'google_translate'

### ISSUE THREAD

**Issue by ServicioIT** [webprice/google_translate_django4#1]
hi. making all steps...

Requirement already satisfied: google-translate-django4 in /home/admin/.local/lib/python3.9/site-packages (0.3)
Requirement already satisfied: django in /home/admin/.local/lib/python3.9/site-packages (from google-translate-django4) (4.1.7)
Requirement already satisfied: asgiref<4,>=3.5.2 in /home/admin/.local/lib/python3.9/site-packages (from django->google-translate-django4) (3.6.0)
Requirement already satisfied: sqlparse>=0.2.2 in /home/admin/.local/lib/python3.9/site-packages (from django->google-translate-django4) (0.4.3)

but, when i try to run the server...

ModuleNotFoundError: No module named 'google_translate'

Any idea? thanks

**Comment by serhii-hrekov** [comment]
the version of Django you're using?

**Comment by ServicioIT** [comment]
Hi, 4.1

On 6 Apr 2023, 4:18 AM -0500, Bro Developer ***@***.***>, wrote:

the version of Django you're using?

**Comment by serhii-hrekov** [comment]
as I understand you're trying to import the module in one of your files. the module has a different name... Check out your backlog, there should be mentioned the line and the file where the error has appeared.

**Comment by serhii-hrekov** [comment]
have you followed this guide https://pypi.org/project/google-translate-django4/ ?

**Comment by ServicioIT** [comment]
yes making this instructions: https://pypi.org/project/google-translate-django4/  
i try to make it run in a new setup, Python 3.11 + Django 4.1.7

django.core.exceptions.ImproperlyConfigured: Cannot import 'translate'. Check that 'google_translate.apps.TranslateConfig.name' is correct.

**Comment by AndrejGorodnij** [comment]
There is error in this django module, in `google_translate/apps.py ` file

```
class TranslateConfig(AppConfig):
    name = "translate"
```
need to be

```
class TranslateConfig(AppConfig):
    name = "google_translate"
```
This changes fix this Import issue.

**Comment by AndrejGorodnij** [comment]
@webprice You need to fix that, and update Pypi package =)

P.S. Дякую за оновлення модуля для 4 версії Джанго!

**Comment by serhii-hrekov** [comment]
> @webprice You need to fix that, and update Pypi package =)
> 
> P.S. Дякую за оновлення модуля для 4 версії Джанго!

чесно кажучи я в шоці що мій модуль хтось юзає. На вихідних постараюся поправити код

**Comment by serhii-hrekov** [comment]
@AndrejGorodnij @ServicioIT 
module updated:
https://pypi.org/project/google-translate-django4/
https://github.com/webprice/google_translate_django4

**Comment by serhii-hrekov** [comment]
@AndrejGorodnij якщо треба оновити модуль - пишіть, я давно не працював з Django, не знаю що там зараз коїться

**Comment by AndrejGorodnij** [comment]
> @AndrejGorodnij якщо треба оновити модуль - пишіть, я давно не працював з Django, не знаю що там зараз коїться

Дякую за пропозицію, але теж вже відійшов від Django, на практиці виявилось що більше борюсь з Django, ніж роблю роботу 😁 пішов на Fastapi та мікросервіси. Бережіть себе. Усього найкращого 🤝
